branch-defaults:
  master:
    environment: valueminer-adapter-dev
    group_suffix: null
deploy:
  artifact: target/valueminer-adapter-0.0.1-SNAPSHOT.jar
global:
  application_name: valueminer-adapter
  branch: develop
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: spring-boot
  repository: null
  sc: git
  workspace_type: Application
